version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f1063d6b0e8b919e25aad49f1ca3d446f5114f8a33881a45f10058abaa3dca64
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
