version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:8cb3d878ccce47f510195d428979990ec130b3866555784ddd304249fed822ec
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
