version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:73b4f6b46642eae8b73b16005dc7123997d3ad5a9cbd657213efea842480ca55
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
