version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f9412c07c7318b6c19cdb9b758bd5c601678a83f8277059c79288dd43fcb7281
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
